Repository hanaro7team1/backend, pull requests merged in 2025-09, with the labels that each got.

#17 [Feat] 부동산 매물 페이지 목록 조회 & 상세 조회 기능 구현
  src/main/java/com/sido/backend/realestate/controller/RealEstateController.java
  src/main/java/com/sido/backend/realestate/dto/RealEstateDetailResponseDTO.java
  src/main/java/com/sido/backend/realestate/dto/RealEstateResponseDTO.java
  src/main/java/com/sido/backend/realestate/entity/RealEstate.java
  src/main/java/com/sido/backend/realestate/entity/RealEstateImage.java
  src/main/java/com/sido/backend/realestate/repository/RealEstateImageRepository.java
  src/main/java/com/sido/backend/realestate/repository/RealEstateRepository.java
  src/main/java/com/sido/backend/realestate/service/RealEstateService.java
  src/main/java/com/sido/backend/realestate/service/RealEstateServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/sido/backend/realestate/repository/RealEstatesRepositoryTest.java
Labels: API, Feature

#24 [Feat] 예약 취소하기
  src/main/java/com/sido/backend/reservation/controller/ReservationController.java
  src/main/java/com/sido/backend/reservation/repository/ReservationDayRepository.java
  src/main/java/com/sido/backend/reservation/service/ReservationService.java
  src/main/java/com/sido/backend/reservation/service/ReservationServiceImpl.java
Labels: API, Feature

#21 [Refactor] 예외처리 & 예약 검증 리팩토링
  src/main/java/com/sido/backend/common/GlobalExceptionHandler.java
  src/main/java/com/sido/backend/common/exception/BadRequestException.java
  src/main/java/com/sido/backend/common/exception/ConflictException.java
  src/main/java/com/sido/backend/common/exception/ForbiddenException.java
  src/main/java/com/sido/backend/reservation/controller/ReservationController.java
  src/main/java/com/sido/backend/reservation/dto/ReservationDetailResponseDTO.java
  src/main/java/com/sido/backend/reservation/repository/ReservationDayRepository.java
  src/main/java/com/sido/backend/reservation/service/ReservationService.java
  src/main/java/com/sido/backend/reservation/service/ReservationServiceImpl.java
  src/main/java/com/sido/backend/reservation/validation/AvailabilityChecker.java
  src/main/java/com/sido/backend/reservation/validation/ReservationValidator.java
Labels: Refactor

#20 [Feat] 예약하기 & 예약 확정 기능 구현
  src/main/java/com/sido/backend/common/GlobalExceptionHandler.java
  src/main/java/com/sido/backend/common/exception/BadRequestException.java
  src/main/java/com/sido/backend/common/exception/ConflictException.java
  src/main/java/com/sido/backend/common/exception/ForbiddenException.java
  src/main/java/com/sido/backend/reservation/controller/ReservationController.java
  src/main/java/com/sido/backend/reservation/dto/ReservationCommonDTOs.java
  src/main/java/com/sido/backend/reservation/dto/ReservationConfirmRequestDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationConfirmResponseDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationCreateRequestDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationCreateResponseDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationDetailResponseDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationListResponseDTO.java
  src/main/java/com/sido/backend/reservation/entity/Reservation.java
  src/main/java/com/sido/backend/reservation/entity/ReservationDay.java
  src/main/java/com/sido/backend/reservation/entity/ResrvStatus.java
  src/main/java/com/sido/backend/reservation/repository/ReservationDayRepository.java
  src/main/java/com/sido/backend/reservation/service/ReservationService.java
  src/main/java/com/sido/backend/reservation/service/ReservationServiceImpl.java
  src/main/java/com/sido/backend/reservation/validation/AvailabilityChecker.java
  src/main/java/com/sido/backend/reservation/validation/ReservationValidator.java
Labels: API, Feature

#23 [Feat] 시골 관리자 전용 마이페이지 기능 구현
  src/main/java/com/sido/backend/member/controller/MyPageController.java
  src/main/java/com/sido/backend/member/dto/MyPageResponseDTO.java
  src/main/java/com/sido/backend/member/dto/PasswordUpdateRequestDTO.java
  src/main/java/com/sido/backend/member/dto/PhoneUpdateRequestDTO.java
  src/main/java/com/sido/backend/member/repository/HostMemberRepository.java
  src/main/java/com/sido/backend/member/service/MemberService.java
  src/main/java/com/sido/backend/member/service/MemberServiceImpl.java
Labels: API, Feature

#29 [Fix] 쿠키-role의 만료시간 설정
  src/main/java/com/sido/backend/member/controller/MemberController.java
Labels: BugFix

#33 [Feat] 시골 관리자- 예약 목록 조회
  src/main/java/com/sido/backend/reservation/controller/ReservationAdminController.java
  src/main/java/com/sido/backend/reservation/dto/ReservationOverviewDTO.java
  src/main/java/com/sido/backend/reservation/repository/ReservationQDslRepository.java
  src/main/java/com/sido/backend/reservation/repository/ReservationQDslRepositoryImpl.java
  src/main/java/com/sido/backend/reservation/service/ReservationService.java
  src/main/java/com/sido/backend/reservation/service/ReservationServiceImpl.java
Labels: API, Feature, Refactor

#31 [Feat] 예약 목록 조회 & 다가오는 가장 가까운 예약 조회
  .gitignore
  build.gradle
  src/main/java/com/sido/backend/config/QueryDslConfig.java
  src/main/java/com/sido/backend/member/controller/MemberController.java
  src/main/java/com/sido/backend/reservation/controller/ReservationAdminController.java
  src/main/java/com/sido/backend/reservation/controller/ReservationController.java
  src/main/java/com/sido/backend/reservation/dto/ReservationCommonDTOs.java
  src/main/java/com/sido/backend/reservation/dto/ReservationConfirmResponseDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationListFilter.java
  src/main/java/com/sido/backend/reservation/dto/ReservationListItemDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationOverviewDTO.java
  src/main/java/com/sido/backend/reservation/dto/ReservationViewStatus.java
  src/main/java/com/sido/backend/reservation/entity/Reservation.java
  src/main/java/com/sido/backend/reservation/repository/ReservationQDslRepository.java
  src/main/java/com/sido/backend/reservation/repository/ReservationQDslRepositoryImpl.java
  src/main/java/com/sido/backend/reservation/repository/ReservationRepository.java
  src/main/java/com/sido/backend/reservation/service/ReservationService.java
  src/main/java/com/sido/backend/reservation/service/ReservationServiceImpl.java
Labels: API, Feature

#37 [Feat] 사랑방 예약 가능(오픈) 날짜 추가 및 변경
  src/main/java/com/sido/backend/config/SecurityConfig.java
  src/main/java/com/sido/backend/reservation/repository/ReservationDayRepository.java
  src/main/java/com/sido/backend/stay/controller/StayAdminController.java
  src/main/java/com/sido/backend/stay/controller/StayController.java
  src/main/java/com/sido/backend/stay/dto/OpenAndReservedDatesDTO.java
  src/main/java/com/sido/backend/stay/repository/StayAvailDateRepository.java
  src/main/java/com/sido/backend/stay/service/StayService.java
  src/main/java/com/sido/backend/stay/service/StayServiceImpl.java
Labels: API, Feature, Refactor

#38 [Feat] 회원탈퇴 api 생성
  src/main/java/com/sido/backend/member/controller/MyPageController.java
  src/main/java/com/sido/backend/member/dto/WithdrawRequestDTO.java
  src/main/java/com/sido/backend/member/service/MemberService.java
  src/main/java/com/sido/backend/member/service/MemberServiceImpl.java
  src/main/java/com/sido/backend/reservation/repository/ReservationRepository.java
Labels: Feature

#39 [Feat] WebSocket을 이용한 실시간 예약 확정 알림 기능 구현
  build.gradle
  gradlew
  src/main/java/com/sido/backend/config/SecurityConfig.java
  src/main/java/com/sido/backend/config/WebSocketConfig.java
  src/main/java/com/sido/backend/reservation/dto/ReservationNotificationDTO.java
  src/main/java/com/sido/backend/reservation/service/ReservationServiceImpl.java
Labels: API, Feature

#40 [Feat] OpenAI 연결해서 설명 자동 생성 api 구현
  .gitignore
  build.gradle
  src/main/java/com/sido/backend/stay/config/S3Config.java
  src/main/java/com/sido/backend/stay/controller/AiController.java
  src/main/java/com/sido/backend/stay/dto/OpenAiResponseDTO.java
  src/main/java/com/sido/backend/stay/service/OpenAiService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: API, Feature, Refactor

#41 [Fix] 회원탈퇴 오류 해결
  src/main/java/com/sido/backend/member/controller/MyPageController.java
  src/main/java/com/sido/backend/member/service/MemberService.java
  src/main/java/com/sido/backend/member/service/MemberServiceImpl.java
  src/main/java/com/sido/backend/reservation/repository/ReservationRepository.java
  src/main/java/com/sido/backend/stay/entity/Stay.java
Labels: BugFix

#46 [Fix] 매물 가격 & 지역 필터링 기능 수정 및 개선
  src/main/java/com/sido/backend/realestate/controller/RealEstateController.java
  src/main/java/com/sido/backend/realestate/repository/RealEstateRepository.java
  src/main/java/com/sido/backend/realestate/service/RealEstateService.java
  src/main/java/com/sido/backend/realestate/service/RealEstateServiceImpl.java
  src/main/resources/data.sql
Labels: BugFix, Feature

#49 [Refactor] 예약 가능 날짜 조회 api 월 구분 안 하도록 (admin/도시 둘 다)
  src/main/java/com/sido/backend/reservation/repository/ReservationDayRepository.java
  src/main/java/com/sido/backend/stay/controller/StayAdminController.java
  src/main/java/com/sido/backend/stay/controller/StayController.java
  src/main/java/com/sido/backend/stay/dto/AvailDatesDTO.java
  src/main/java/com/sido/backend/stay/dto/OpenAndReservedDatesDTO.java
  src/main/java/com/sido/backend/stay/repository/StayAvailDateRepository.java
  src/main/java/com/sido/backend/stay/service/StayService.java
  src/main/java/com/sido/backend/stay/service/StayServiceImpl.java
Labels: Refactor

#50 [Refactor] 주소 정규식 카카오 라이브러리에 맞춤
  src/main/java/com/sido/backend/stay/utils/AddressRegionGrouper.java
  src/main/java/com/sido/backend/stay/utils/KoreanAddressParser.java
  src/main/resources/data.sql
Labels: Refactor

#58 [Feat] 예약 리포지토리 테스트
  src/main/java/com/sido/backend/festival/controller/FestivalController.java
  src/test/java/com/sido/backend/reservation/repository/ReservationRepositoryTest.java
Labels: Feature
